### ISSUE TITLE
What's the coverage of Key:duration from professional data

### ISSUE THREAD

**Issue by CodeBear801** [Telenav/osrm-backend#10]
[Description]
OSRM use "duration" for ferry/shuttle_train's travel time, which might be helpful if:
- Have reasonable coverage
- Valid value

Here is the description for duration:
https://wiki.openstreetmap.org/wiki/Key:duration

Here is the doc for OSRM logic:
https://github.com/Telenav/open-source-spec/blob/master/osrm/doc/weight_and_duration_calculation_in_osrm.md

**Comment by wangyoucao577** [comment]
There's no `key:duration` in our data..
