### ISSUE TITLE
integration/pkg/api will cause import cycle

### ISSUE THREAD

**Issue by CodeBear801** [Telenav/osrm-backend#129]
When trying to use corrdinate.Coordinates in other files, such as trafficproxy/flow_extension.go(just for testing), will failed to import.

Otherwise might cause import cycle.

**Comment by CodeBear801** [comment]
May be should move `coordinate` and `genericoptions` from `integration/pkg/api/osrm` to `integration/pkg/api/common`

**Comment by wangyoucao577** [comment]
The `coordinate` definition comes from OSRM, so I perfer to put it there. Other definition maybe different name/format/precision, etc. 
What do you want to test in `trafficproxy` with this? `traffproxy` has its own defined `Location` instead.

**Comment by CodeBear801** [comment]
My bad, its the local change in api make the import cycle.

corrdinate is osrm specific, I think current strategy is good: `integration/pkg/api/osrm`
