### ISSUE TITLE
Refactor `api/osrm` package design

### ISSUE THREAD

**Issue by wangyoucao577** [Telenav/osrm-backend#140]
As discussed in https://github.com/Telenav/osrm-backend/pull/139#issuecomment-576969284, let's consider to use `internal` package to hide some implementation details, then put all interfaces at the root of `api/osrm` package. 

The target is to archieve below features for client: 
- use `osrm.Coordinate` instead of `coordinate.Coordinate`;
- use `osrm.RouteRequest` instead of `route.Request`;

Let's use the `api/osrm/coordinate` package as a example. 
Currently the `api/osrm/coordinate` package is independent and hide implementation inside. But if we want to archieve `osrm.Coordinate` we have to move everything out to the `api/osrm` package. It will lead to a big `api/osrm` package, difficult to manage and maintain. But if we hide the implementation of `Coordinate` into `internal` package, we may possible only put definition in `api/osrm`, result will be clear.

**Comment by CodeBear801** [comment]
Have definition in `api/osrm` and put util/helper/logic into other place is a clear design, let me use code to confirm, still use `coordinate.go` as an example:
- All type definition in `api/osrm/coordinate.go`
```go
package osrm

// Coordinate represents lat/lon of a GPS point.
type Coordinate struct {
	Lat float64
	Lon float64
}

type ICoordinate interface {
         String(c *Coordinate) string;
         ParseCoordinate(str string)(Coordinate, error);
}

// Coordinates represents a list of GPS points.
type Coordinates []Coordinate

// interface ...

```

- Put implementation of osrm coordinate interface in `pkg/internal/osrm/coordinate.go`
- User will use osrm.Coordinate when define their types
- User will use osrm.ParseCoordinate() when calling implementations
- If I want to implement different `coordinate` for search, like `str(lat, lon)` not osrm's `str(lon,lat)`, I could make a implementation in `pkg/internal/search/coordinate.go`

**Comment by wangyoucao577** [comment]
Yes, something like this. But I'm not sure whether it's possible in `Golang`. We could have a try.

**Comment by CodeBear801** [comment]
I tried to define coordinate.go under `pkg/api/osrm/` and then make impl to `internal`, but go error of `cannot define new methods on non-local type osrm.Coordinate`

Here is `pkg/api/osrm/coordinate.go`

```go
package osrm

// Coordinate represents lat/lon of a GPS point.
type Coordinate struct {
	Lat float64
	Lon float64
}

// CoordinateUtil defines serialize and deserialize function for Coordinate
type CoordinateUtil interface {
	String() string
	ParseCoordinate(str string) (Coordinate, error)
}

// Coordinates represents a list of GPS points.
type Coordinates []Coordinate

// CoordinatesUtil defines serialize and deserialize function for Coordinates
type CoordinatesUtil interface {
	String() string
	ParseCoordinate(str string) (Coordinates, error)
}

``` 

Here is `internal/coordinate/coordinateutil.go`

```go
// String convert osrm.Coordinate to string. Lat/lon precision is 6.
func (c osrm.Coordinate) String() string {

	s := fmt.Sprintf("%.6f%s%.6f", c.Lon, api.Comma, c.Lat)
	return s
}
```

**Comment by wangyoucao577** [comment]
Yes, `internal` is totally different with with `.h -> .cpp`. It will not work that simplity separate implementation codes with its type definition.  
Actually the idea is not clearly enough in my mind. Let's re-think it again, and don't forget the initial idea: use `osrm.yyy` instead of `xxx.yyy`.       
I'll try to write some code later, we just need to figure out a better approach than the current one. Maybe simply move codes in `api/osrm` package is ok.

**Comment by wangyoucao577** [comment]
I tried below solution:     
- Package api/osrm
```go
// Package api/osrm 
// coordinate.go 

type Coordinate struct {
	Lat float64
	Lon float64
}

// ParseCoordinate parses string to coorinate.
func ParseCoordinate(str string) (Coordinate, error) {
	c := Coordinate{}
	lat, lon, err := coordinateimpl.ParseCoordinate(str)
	if err != nil {
		return c, err
	}
	c.Lat = lat
	c.Lon = lon
	return c, nil
}
```
- Package api/osrm/internal/coordinateimpl
```go
// Package api/osrm/internal/coordinateimpl
// coordinate.go 

func ParseCoordinate(str string) (float64, float64, error) {
	//c := osrm.Coordinate{}

	splits := strings.Split(str, api.Comma)
	if len(splits) < 2 {
		return 0, 0, fmt.Errorf("parse %s to Coordinate failed", str)
	}

	var err error
	var lat, lon float64
	if lon, err = strconv.ParseFloat(splits[0], 64); err != nil {
		return 0, 0, fmt.Errorf("parse Lon from %s failed", str)
	}
	if lat, err = strconv.ParseFloat(splits[1], 64); err != nil {
		return 0, 0, fmt.Errorf("parse Lan from %s failed", str)
	}
	return lat, lon, nil
}

```
It hides the implementation in `api/osrm/internal/coordinateimpl`. But as you said, it's different with `.h/.cpp` pattern. The downside is that it uses two layers of structures for passing(in `api/osrm/internal/coordinateimpl` returns `lon,lat` instead of `osrm.Coordinate` directly). It might be reasonable if we have a lot of logic expect to hide, but here I think it's also overfitting.    
Let's go with the simple solution: put the `Coordinate` in package `api/osrm`.
