### ISSUE TITLE
Distinguish profiles between OSM PBF and TelenavUniDB PBF

### ISSUE THREAD

**Issue by wangyoucao577** [Telenav/osrm-backend#181]
We're going to use OSRM based on two data sets as input:     
- OSM PBF
- Telenav UniDB PBF

It seems that the profiles(`*.lua`) have to be distinguished since there a lot of differences between the two data sets, otherwise we'll difficult to avoid profiles change for Telenav UniDB PBF also affects behavior on OSM.      

Here's my proposal:      
- `mkdir -p profiles/tn-unidb profiles/tn-unidb/lib`
- `cp profiles/car.lua profiles/tn-unidb/`
- `cp profiles/lib/xxx.lua profiles/tn-unidb/lib/xxx.lua` once we want to make some change that only expect to affect on Telenav UniDB PBF 
- The `*.lua`s that we don't want to make any change and can be used by both OSM PBF and Telenav UniDB PBF, don't copy them. 
- revert PR https://github.com/Telenav/osrm-backend/pull/67, make sure the profiles for OSM PBF are clean.

**Comment by wangyoucao577** [comment]
How's your opinion? @hellotechx  @CodeBear801  @wuliwalateng 
We'd better make a decision and implement it before https://github.com/Telenav/osrm-backend/issues/134 and https://github.com/Telenav/osrm-backend/issues/108.

**Comment by CodeBear801** [comment]
Separate telenav specific files with original osrm.osm files is needed:
- we could create a certain pattern like `unidb-xxx.lua` and put them into `profiles/`
- for all script files needed should duplicate and name with new patterns
- [optional] during copy, could based on parameters to copy certain files and rename them back to `car.lua`, `way.lua` etc.

**Comment by wangyoucao577** [comment]
I think distinguish them by file name pattern is good too. 

Based on a quick discussion with @CodeBear801 , let's to try finalize the proposal: 
- duplicate any file if need to modify for Telenav UniDB PBF with a certain file name pattern
  - duplicate a `profiles/car-unidb.lua` from `profiles/car.lua`
  - duplicate a `profiles/lib/way_handlers-unidb.lua` from `profiles/lib/way_handlers.lua`
  - etc.     
- if `xxx-unidb.lua` exist, the `car-unidb.lua` will only invoke functions from `xxx-unidb.lua` instead of `xxx.lua`. In another word, the `car-unidb.lua` should NOT invoke both `xxx-unidb.lua` and `xxx.lua`.   
- the *.luas that we don't want to make any change and can be used by both OSM PBF and Telenav UniDB PBF, don't duplicate them. 
- data compilation pipeline will support to choose `car.lua` or `car-unidb.lua`, not need to copy/overwrite by script.    
- there should be a `README.md` under `profiles` folder to describe above rules and lua change logs(this change for what attribute, etc). 
- revert PR #67, make sure the profiles for OSM PBF are clean, and fix it based on new rule. 


Let's move forward if no more question.
