### ISSUE TITLE
Propose to import new dependencies for go geometries

### ISSUE THREAD

**Issue by CodeBear801** [Telenav/osrm-backend#185]
- Functionality: encoding and decoding polyline in google format
Candidate: https://github.com/twpayne/go-polyline

- Functionality: calculate great circle distance
Candidante: https://github.com/kellydunn/golang-geo
https://github.com/paulmach/go.geo
https://github.com/paulmach/orb

https://github.com/golang/geo should be the best candidate, but I just found following code in `point.go`
```go
// Distance returns the angle between two points.
  func (p Point) Distance(b Point) s1.Angle {
          return p.Vector.Angle(b.Vector)
  }
```
Plan to go with https://github.com/kellydunn/golang-geo at first, later when found related functionality in S2 then replace which with S2 functionality.

**Comment by CodeBear801** [comment]
golang-geo seems imports lots of other dependencies we don't need:
![image](https://user-images.githubusercontent.com/16873751/75398600-fcf9bb00-58ae-11ea-9326-4f01e140d62b.png)
May be its better to implement great circle distance function in our code.

**Comment by CodeBear801** [comment]
https://play.golang.org/p/ts4WltGUvRN

**Comment by wangyoucao577** [comment]
What about https://godoc.org/github.com/blevesearch/bleve/geo? 
I have used its https://godoc.org/github.com/blevesearch/bleve/geo#Haversin in playback.

**Comment by wangyoucao577** [comment]
@CodeBear801  what's problem of this? 

> 
> https://github.com/golang/geo should be the best candidate, but I just found following code in `point.go`
> 
> ```go
> // Distance returns the angle between two points.
>   func (p Point) Distance(b Point) s1.Angle {
>           return p.Vector.Angle(b.Vector)
>   }
> ```
>

**Comment by CodeBear801** [comment]
> What about https://godoc.org/github.com/blevesearch/bleve/geo?
> I have used its https://godoc.org/github.com/blevesearch/bleve/geo#Haversin in playback.

I think this one is better

**Comment by CodeBear801** [comment]
> @CodeBear801 what's problem of this?
> 
> > https://github.com/golang/geo should be the best candidate, but I just found following code in `point.go`
> > ```go
> > // Distance returns the angle between two points.
> >   func (p Point) Distance(b Point) s1.Angle {
> >           return p.Vector.Angle(b.Vector)
> >   }
> > ```

This function returns angle not distance, I haven't find great circle distance's code yet
```
Angle returns the interior angle at the vertex B in the triangle ABC. The
return value is always in the range [0, pi]. All points should be
normalized. Ensures that Angle(a,b,c) == Angle(c,b,a) for all a,b,c.

The angle is undefined if A or C is diametrically opposite from B, and
becomes numerically unstable as the length of edge AB or BC approaches
180 degrees.
```

**Comment by CodeBear801** [comment]
Will use `https://godoc.org/github.com/blevesearch/bleve/geo` and `https://github.com/kellydunn/golang-geo` for next step.
