### ISSUE TITLE
Use master as default branch instead of current master-telenav

### ISSUE THREAD

**Issue by wangyoucao577** [Telenav/osrm-backend#188]
Currently we're using `master-telenav` as default branch because we hope to keep `master` to sync with the original [Project-OSRM/osrm-backend](https://github.com/Project-OSRM/osrm-backend) repo's `master`. But I feel that the name `master-telenav` is a little too long and not that explicitly to team(it breaks the Git's convention that always use `master` as default branch). Also, it will lead to some confusion if people need to import our golang packages(usually import xxx@master to find the latest but that's not correct in our repo). 
 
Here's the new proposal: 
- create new branch `master-projectosrm` to sync/track with the `master` that fork from 
- sync `master` with current `master-telenav`, then use `master` as default branch of this repo. 
  - Github use `master` as default branch to show pages
  - later PR should always target to `master`    
  - deprecate the old `master-telenav` 

@CodeBear801  @hellotechx  How's your opinion? I'll do the change if you're ok.

**Comment by CodeBear801** [comment]
@wangyoucao577 Please go ahead.

**Comment by wangyoucao577** [comment]
I have created `master-projectosrm` instead of original `master`. 
When we have a chance that all PR have been merged, I'll sync `master` with `master-telenav` and make it as default.

**Comment by wangyoucao577** [comment]
Done. Also modified wiki https://github.com/Telenav/osrm-backend/wiki/Contribution-Guidelines#pull-request-target-branch
