### ISSUE TITLE
OSRM integrate with telenav’s traffic service

### ISSUE THREAD

**Issue by CodeBear801** [Telenav/osrm-backend#2]
[Description]
- The communication between OSRM and traffic service
- How OSRM work in Telenav's cloud archicture

[Delivery] 
- Flow chart to describe coordination with traffic service
- Create detail tasks for impl and integration

**Comment by wangyoucao577** [comment]
draft design: https://github.com/Telenav/osrm-backend/blob/feature/with-telenav-traffic/docs/design/osrm-with-telenav-traffic.md

**Comment by wangyoucao577** [comment]
design: https://github.com/Telenav/osrm-backend/blob/master-telenav/docs/design/osrm-with-telenav-traffic.md
