### ISSUE TITLE
Extract timezone and daylight_saving for historical speeds

### ISSUE THREAD

**Issue by wangyoucao577** [Telenav/osrm-backend#219]
- Extract **timezone** and **daylight_saving** from UniDB PBF.     
- Append them to the historical speeds file or generate a new file with mapping wayid-timezone,daylight_saving.     

This a subtask of https://github.com/Telenav/osrm-backend/issues/150

**Comment by wangyoucao577** [comment]
I'm going to refactor the `cmd/wayid2nodeids-extractor` to achieve this better.

**Comment by wangyoucao577** [comment]
Since extract timezone/daylight_saving could only extract for ways have historical speeds, I think a better way maybe have another `cmd/wayid2timezone-extractor`, which takes both pbf and historical speed file as input and generate a **wayid,timezone,daylight_saving** mapping csv as outuput. The new `cmd/wayid2timezone-extractor` will more intuitive, the main cons is need to scan the pbf twice.  

After go through the current `cmd/wayid2nodeids-extractor`, I have some questions: 
- I found a [isNavigableWay](https://github.com/Telenav/osrm-backend/blob/319420c584680f7fb307b9cc2d45b85c5cfda52d/integration/cmd/wayid2nodeid-extractor/wayid2nodeids_extractor.go#L69) improvement here for unidb, but is it really useful? I think most of ways in unidb are navigable, aren't they? Can we remove it? 
- If go with a new binary `cmd/wayid2timezone-extractor`, I think it's better to have a package `unidbpatcher` to unify the [trimNavigableWaySuffix](https://github.com/Telenav/osrm-backend/blob/319420c584680f7fb307b9cc2d45b85c5cfda52d/integration/cmd/wayid2nodeid-extractor/wayid2nodeids_extractor.go#L72) logic, I'll go with it in implementation. 

How's your idea? @CodeBear801

**Comment by CodeBear801** [comment]
> Since extract timezone/daylight_saving could only extract for ways have historical speeds, I think a better way maybe have another `cmd/wayid2timezone-extractor`, which takes both pbf and historical speed file as input and generate a **wayid,timezone,daylight_saving** mapping csv as outuput. The new `cmd/wayid2timezone-extractor` will more intuitive, the main cons is need to scan the pbf twice.
> 
> After go through the current `cmd/wayid2nodeids-extractor`, I have some questions:
> 
> * I found a [isNavigableWay](https://github.com/Telenav/osrm-backend/blob/319420c584680f7fb307b9cc2d45b85c5cfda52d/integration/cmd/wayid2nodeid-extractor/wayid2nodeids_extractor.go#L69) improvement here for unidb, but is it really useful? I think most of ways in unidb are navigable, aren't they? Can we remove it?
> * If go with a new binary `cmd/wayid2timezone-extractor`, I think it's better to have a package `unidbpatcher` to unify the [trimNavigableWaySuffix](https://github.com/Telenav/osrm-backend/blob/319420c584680f7fb307b9cc2d45b85c5cfda52d/integration/cmd/wayid2nodeid-extractor/wayid2nodeids_extractor.go#L72) logic, I'll go with it in implementation.
> 
> How's your idea? @CodeBear801

For #1, we could remove it after a profile.  But I feel might not.
My thinking is, in PBF, not every way is navigable, some of them is for `rivers`, some might just as a `line`.  
It could be one generate a relation for `polygon`, and its members are `ways`, and each `way` contains `nodes`

For #2, Agree.  Put unidb specific knowledge into a separate package.
