### ISSUE TITLE
Integration failed between OSRM custmization and Telenav traffic

### ISSUE THREAD

**Issue by CodeBear801** [Telenav/osrm-backend#22]
Issue description:
Getting data from traffic server and run customization we got such result:
```
[info] Loaded /Users/xunliu/Desktop/data/us_here_nv/traffic.csv with 6727490values
[info] In total loaded 1 file(s) with a total of 6727236 unique value
[info] Used 4220514 speeds from LUA profile or input map
[info] Used 0 speeds from /Users/xunliu/Desktop/data/us_here_nv/traffic.csv
[info] Updating segment data took 195.301ms.
[info] In total loaded 0 file(s) with a total of 0 unique values
[info] Done reading edges in 2609.77ms.
...
```
Which means value from traffic.csv isn't match with OSRM.

Summary:
Issue is due to traffic component dropped original pbf's node id, so additional mapping need to be applied.
A quick solution is: traffic component pass mapping of <wayid, speedmapping>, but preprocessing pbf we generate mapping of <wayid, nodeids>, and by another program we will convert traffic result to <from_node_id, to_node_id, speed> which is expected by OSRM customization.
Current performance benchmark is: getting traffic data from traffic service takes about 20 seconds, then will need another 70 seconds to generate csv file for OSRM.  

We continue integration with this version but start several other issue to optimize the performance.

Follow up issue:
#30
#31

**Comment by CodeBear801** [comment]
Root cause: 
Node id from traffic server is internal nodeid not pbf nodeid, while OSRM could not identify internal nodeid.

Steps of reproducing:
#1. Node in traffic.csv looks like this:
```
==> traffic.csv <==
12593731,12593730,21
21234889,21234888,21
16868877,11418573,20
28905164,28906317,22
```
#2. Query to internal db for wayid
```
UniDB_HERE_NA18Q1_18072619_RV_20180726042413_DEV=# select id, nodes from public.ways where id=957334668100;
      id      |                                                      nodes                                                       
--------------+------------------------------------------------------------------------------------------------------------------
 957334668100 | {976654416102,9573346680001101,9573346680002101,9573346680003101,9573346680004101,9573346680005101,837195203102}
```

PBF's node id is much longer than the one got from traffic server.  I think its due to traffic server's dependency is internal data access API which only generate internal node id which OSRM expects PBF node id.

**Comment by CodeBear801** [comment]
Two solution for solving this issue:

#1. Make modification on traffic side, generate node id OSRM expected.  That one need to discuss with traffic server, I don't think its easy because its dependency is internal data access layer.

#2. Make modification on OSRM server side, traffic side generate <wayid - speed> mapping table, and on OSRM server side covert such table to <nodeid - speed>
There also has multiple choice for #2:
solution | comments | pros | cons
---|---|---|---
Implement additional tool | It will load both original data's PBF and data from traffic server, generate file with <from_node_id, to_node_id, speed> | - No modification on OSRM main logic | - PBF file(10 ~ 20GB) need to be packaged in release package.  - Performance challenge

**Comment by CodeBear801** [comment]
For "Implement additional tool"

#1. Use go language to development
     Go parser for pbf: https://github.com/substack/osm-pbf-parser
     We could load result from traffic servers into a map and holds them in memory, then parsing PBF should use go routine to parse each of pbf's primitive blob, output result to go channel and use another go routine keep on write result to output.
     
     To do: need some experiment on go pbf parser

#2. Use osmium(C++11) to development
      Load result from traffic servers into a map and holds them in memory, then implement OSMIUM parser to convert each way to from_node, to_node.  
      Inside of OSMIUM, there are thread pool and message queue already be implemented and its target is high performance.  I feel it could be easier to reach high performance.

Proposal: Investigate on go pbf parser, implement go version first.
                 If performance is not as expected, then try with osmium.

**Comment by CodeBear801** [comment]
Release pbf with final data is inconvenient, what we need is <wayid, nodes> mapping table.

Solution:
- During pre-processing step, we could process pbf and generate mapping table about <way, nodes> files, it could be huge.  We need consider how we could handle result concurrently
- Load traffic server's result into memory
- Iterate <way, nodes> table, if find specific way in traffic server's response, then put result into channel for output.  Result should put into output channel based on trunk, must avoid put them one by one.
- Output result to csv.

**Comment by CodeBear801** [comment]
Testing result, based on [go's pbf decoder](https://github.com/qedus/osmpbf) + HERE data, performance is good but need large data to test.

I could generate following information:
WayID: 28381045100, [19473471102 283810450001101 19473488102],
WayID: 28381046100, [19475072102 19475073102],
WayID: 28381047100, [19475458102 283810470001101 19475456102],
WayID: 28381048100, [19475073102 283810480001101 283810480002101 19475089102],
WayID: 28381049100, [19474972102 19474973102],
WayID: 28381050100, [19475378102 19475379102],
WayID: 28381051100, [19475092102 19475097102],
WayID: 28381052100, [19475341102 19475347102],
WayID: 28381053100, [19475347102 19475366102],
WayID: 28381054100, [19485149102 19485143102],
WayID: 28381055100, [19475069102 283810550001101 19475078102],
WayID: 28381056100, [19475371102 19475767102],
WayID: 28381057100, [19475479102 19475677102],
WayID: 28381058100, [19485428102 283810580001101 19475876102],
WayID: 28381059100, [19475634102 283810590001101 19475658102],
WayID: 28381060100, [19475538102 19475540102],
WayID: 28381061100, [19476297102 283810610001101 19476298102],

**Comment by wangyoucao577** [comment]
I remember we have a step to shorten ids when export PBF from UniDB.  I doubt that we're using different PBF relative to traffic team. Let me talk to them for details. I think we don't need to implement the <wayid, nodes> mapping table.

**Comment by wangyoucao577** [comment]
Checked with our data team, they didn't do anything when export PBF from UniDB. It should be some logic in traffic handler.

**Comment by CodeBear801** [comment]
From yesterday's email, I noticed that traffic part's compiler depends on TDK not ngx related solution.  Then I think we could have a check whether we could get original node id from TDK, if so that's the most convenient one.

**Comment by wangyoucao577** [comment]
Checked with traffic team, the original node ids from PBF seem also be discarded during their process. So we may have to implement our own mapping from `way_id` to `from_node/to_node`.  
Basic idea I agree https://github.com/Telenav/osrm-backend/issues/22#issuecomment-503344729. 
We can generate the mapping during `compile_data`, save it as a `ways_to_nodes.csv` or something similar. During `routed_startup`, we'll load the `ways_to_nodes.csv` in `osrm_traffic_updater`, convert `wayid` to `fromId,toId` before write to `traffic.csv`.

**Comment by CodeBear801** [comment]
Some adjustment
#1. wayid2nodeids-extract
- Input: original PBF(HERE, OSM)
- output: way_id-> all node ids
  OSRM expects: 
```
from_node_id, inner_node_id_1, speed_value
inner_node_id_1, inner_node_id_2, speed_value
inner_node_id_2, to_node_id, speed_value                             
```
A simple .csv is good enough

#2. Modify osrm_traffic_updater
- Load way_id->from_id, to_id into memory
- for each traffic object in thrift format, convert from
```
wayid, speed
```
to
```
from_node_id, inner_node_id_1, speed_value
inner_node_id_1, inner_node_id_2, speed_value
inner_node_id_2, to_node_id, speed_value   
```
Then save to traffic.csv file.

**Comment by CodeBear801** [comment]
NA data statistic: 1GB

**Comment by wangyoucao577** [comment]
@CodeBear801 we don't need to mock. `wayid` already exists, I just discard them when write to `traffic.csv` in `osrm_traffic_updater`.

**Comment by wangyoucao577** [comment]
@CodeBear801  The estimation of size is very valuable! I think we can have a simple `.csv` to store the mapping in first version. Then we can consider to use a better way instead to handle such big data.

**Comment by CodeBear801** [comment]
> @CodeBear801 we don't need to mock. `wayid` already exists, I just discard them when write to `traffic.csv` in `osrm_traffic_updater`. See codes in
> 
> https://github.com/Telenav/osrm-backend/blob/147b6e520f564e8ad39de5633b21a5819ac00b95/traffic_updater/go/osrm_traffic_updater/osrm_traffic_updater.go#L54
> 
> and
> https://github.com/Telenav/osrm-backend/blob/147b6e520f564e8ad39de5633b21a5819ac00b95/traffic_updater/go/gen-go/proxy/proxy.go#L30

**Comment by CodeBear801** [comment]
@wangyoucao577 
Running integration test on ec2d machine, updates
1. Generate speed table takes 69 seconds.  Consider communication time with traffic server, total time could be 90~120 seconds.  
   I think its good for integration for next step, but will look more for optimization, it would be great the total time cost at about 10 seconds range.

2. @wangyoucao577 I feel traffic part changed the API definition, please confirm.
    Original logic met issue as below:
```
getting flows
get flows failed: *proxy.Flow error reading struct: Required field FromId is not set
```
  I changed protocol for  fromnodeid and tonodeid, from required to optional, and then regenerate go code using thrift 0.12.0

**Comment by wangyoucao577** [comment]
@CodeBear801 Yes, the RPC protocol is changed. The `fromId/toId` were set to optional and disabled on `proxy`. I have filed the PR https://github.com/Telenav/osrm-backend/pull/29 to adapter this change. Please help to review, approve and merge into `master-telenav`. Once it's merged, you can rebase your branch against `master-telenav` to have this update.

**Comment by wangyoucao577** [comment]
Now we can get more flows for NA: 
```bash
./bin/osrm_traffic_updater -c 10.189.102.81 -d=false
connect traffic proxy 10.189.102.81:6666
getting flows
got flows count: 16130308
get flows time used: 23.592399 seconds
```

**Comment by CodeBear801** [comment]
Copy that.
I think we would load "small/faster" data into memory and then iterate another one.  For this version, if not optimize wayid2nodeid table then this part would be the biggest part, but if we could make that smaller and quicker to load then would be another story.
For next step, let's try to optimize the size of wayid2nodeid table and see how long would system to build memory structure for which.  
In general, I agree the idea of load local data into memory and iterate data coming from remotely.
