### ISSUE TITLE
Oasis - Prepare for charge station input

### ISSUE THREAD

**Issue by CodeBear801** [Telenav/osrm-backend#237]
Subtask of #231

### Input
For charge station data, or POI data, they usually recorded in database.  First step would be dump this database into `csv` format, each line represent information for a single charge station.

csv
![image](https://user-images.githubusercontent.com/16873751/77694625-93c99e00-6f67-11ea-8eb0-e99d502e6dfa.png)

### Processing flow
```
Telenav's Database(postGIS) 
       -> csv 
               -> adjust column name 
                       -> convert csv to json 
                                 -> decoding json
```
More details could go to here: https://github.com/Telenav/osrm-backend/issues/237#issuecomment-603367508

### Target format

Electricity charge stations, expect input in JSON format follow OSM's tag definition about [node](https://wiki.openstreetmap.org/wiki/Node) and [charging_station](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcharging_station), example:
```json
{
   "id": 12345,
   "lat": 51.5173639,
   "lon": -0.140043,
   "amenity": "charging_station",
   "operator": "NOFT",
   "fee": "yes",
   "capacity":4,
}
```
- Later could implement more input connector: pbf, csv, etc.
- We want to make this `json` format as `protocol` for following processing
- A sample JSON record could be found [here](https://github.com/Telenav/osrm-backend/blob/240bb5b0a90080d6686191c2ff09c2d5a9160d3b/integration/service/poiloader/sample_input.json#L2)
-  Json record sample:
```
[{"id":12345,"vendor_code":"NOFT","vendor_poi_id":"NOFT-10_NREL99930@-@NOCO-37145190@-@NOCO-996595530","lat":0.0,"lon":0.0,"nav_lat":0.0,"nav_lon":0.0,"dis_lat":0.0,"dis_lon":0.0,"map_link_id":12345,"side_of_street":"+","country":"USA","space_id":"USA_CA","airport_code":"NULL","is_national":false,"is_state_importance":false,"is_city_importance":false,"fax":"NULL","phone":8054662325,"encoded_phone":"Prefix=1,CountryCode=1,AreaCode=805,LocalNumber=4662325,RawData=8054662325,Preferred=1,E164=+18054662325,PhoneType=phone","email":"NULL","web_url":"NULL","category_id_gather":"xxx``xxx``xxx","chain_gather":"1364@-@@-@",,"hilbert":2.32E+11,"amenity":"charging_station"},]
```

**Comment by CodeBear801** [comment]
## Flow

Telenav's Database(postGIS) -> csv -> adjust column name -> convert csv to json -> decoding json

**Comment by wangyoucao577** [comment]
> Subtask of #231
> 
> ### Input
> For charge station data, or POI data, they usually recorded in database. First step would be dump this database into `csv` format, each line represent information for a single charge station.
> 
> csv record sample:
> 
> ```
> [{"id":12345,"vendor_code":"NOFT","vendor_poi_id":"NOFT-10_NREL99930@-@NOCO-37145190@-@NOCO-996595530","lat":0.0,"lon":0.0,"nav_lat":0.0,"nav_lon":0.0,"dis_lat":0.0,"dis_lon":0.0,"map_link_id":12345,"side_of_street":"+","country":"USA","space_id":"USA_CA","airport_code":"NULL","is_national":false,"is_state_importance":false,"is_city_importance":false,"fax":"NULL","phone":8054662325,"encoded_phone":"Prefix=1,CountryCode=1,AreaCode=805,LocalNumber=4662325,RawData=8054662325,Preferred=1,E164=+18054662325,PhoneType=phone","email":"NULL","web_url":"NULL","category_id_gather":"xxx``xxx``xxx","chain_gather":"1364@-@@-@",,"hilbert":2.32E+11,"amenity":"charging_station"},]
> ```
> 
> ### Processing flow
> ```
> Telenav's Database(postGIS) 
>        -> csv 
>                -> adjust column name 
>                        -> convert csv to json 
>                                  -> decoding json
> ```
> 
> More details could go to here: [#237 (comment)](https://github.com/Telenav/osrm-backend/issues/237#issuecomment-603367508)
> 
> ### Target format
> Electricity charge stations, expect input in JSON format follow OSM's tag definition about [node](https://wiki.openstreetmap.org/wiki/Node) and [charging_station](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcharging_station), example:
> 
> ```json
> {
>    "id": 12345,
>    "lat": 51.5173639,
>    "lon": -0.140043,
>    "amenity": "charging_station",
>    "operator": "NOFT",
>    "fee": "yes",
>    "capacity":4,
> }
> ```
> 
> * Later could implement more input connector: pbf, csv, etc.
> * We want to make this `json` format as `protocol` for following processing
> * A sample JSON record could be found [here](https://github.com/Telenav/osrm-backend/blob/240bb5b0a90080d6686191c2ff09c2d5a9160d3b/integration/service/poiloader/sample_input.json#L2)

The original format is not csv. It's json actually (after remove head `[` and tail `]`). It should be able to parse by json library directly. The sample json you metiond is a json with line endings for better human readable, some json libraries support it. But without line endings is more common json.

**Comment by CodeBear801** [comment]
> > Subtask of #231
> > ### Input
> > For charge station data, or POI data, they usually recorded in database. First step would be dump this database into `csv` format, each line represent information for a single charge station.
> > csv record sample:
> > ```
> > [{"id":12345,"vendor_code":"NOFT","vendor_poi_id":"NOFT-10_NREL99930@-@NOCO-37145190@-@NOCO-996595530","lat":0.0,"lon":0.0,"nav_lat":0.0,"nav_lon":0.0,"dis_lat":0.0,"dis_lon":0.0,"map_link_id":12345,"side_of_street":"+","country":"USA","space_id":"USA_CA","airport_code":"NULL","is_national":false,"is_state_importance":false,"is_city_importance":false,"fax":"NULL","phone":8054662325,"encoded_phone":"Prefix=1,CountryCode=1,AreaCode=805,LocalNumber=4662325,RawData=8054662325,Preferred=1,E164=+18054662325,PhoneType=phone","email":"NULL","web_url":"NULL","category_id_gather":"xxx``xxx``xxx","chain_gather":"1364@-@@-@",,"hilbert":2.32E+11,"amenity":"charging_station"},]
> > ```
> > 
> > 
> > ### Processing flow
> > ```
> > Telenav's Database(postGIS) 
> >        -> csv 
> >                -> adjust column name 
> >                        -> convert csv to json 
> >                                  -> decoding json
> > ```
> > 
> > 
> > More details could go to here: [#237 (comment)](https://github.com/Telenav/osrm-backend/issues/237#issuecomment-603367508)
> > ### Target format
> > Electricity charge stations, expect input in JSON format follow OSM's tag definition about [node](https://wiki.openstreetmap.org/wiki/Node) and [charging_station](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcharging_station), example:
> > ```json
> > {
> >    "id": 12345,
> >    "lat": 51.5173639,
> >    "lon": -0.140043,
> >    "amenity": "charging_station",
> >    "operator": "NOFT",
> >    "fee": "yes",
> >    "capacity":4,
> > }
> > ```
> > 
> > 
> > 
> > * Later could implement more input connector: pbf, csv, etc.
> > * We want to make this `json` format as `protocol` for following processing
> > * A sample JSON record could be found [here](https://github.com/Telenav/osrm-backend/blob/240bb5b0a90080d6686191c2ff09c2d5a9160d3b/integration/service/poiloader/sample_input.json#L2)
> 
> The original format is not csv. It's json actually (it's a json array with head `[` and tail `]`). It should be able to parse by json library directly. The sample json you metiond is a json with line endings for better human readable, some json libraries support it. But without line endings is more common json.

My bad, I put a converted json record there :(
Update the first comment.

**Comment by CodeBear801** [comment]
It is also possible to directly dump `sql` query result to `json` format.

**Comment by wangyoucao577** [comment]
Aha! Now it makes sense. But I still think the `csv-to-json` is not a good name since the convertion is not generic but for specified domain. How about rename it to something like `poi-preprocess` or `poi-unify`? Or maybe `poi-converter` that possible to support converting between `csv`,`json`,`pbf`, etc.
