### ISSUE TITLE
Experiment OSRM cucumber

### ISSUE THREAD

**Issue by CodeBear801** [Telenav/osrm-backend#244]
Experiment OSRM cucumber:
- How to make cucumber work in local
- How to make tests automatic running
- How to write cucumber tests

**Comment by CodeBear801** [comment]
## How to make cucumber work(on local)
- Following information here: https://github.com/Project-OSRM/osrm-backend/wiki/Cucumber-Test-Suite#install-dependencies
- Try to set env up in docker
```
// build docker image
docker build -t osrm-dev-experiment-cucumber:v1 -f docker-orchestration/osrm-backend-dev/Dockerfile .

// start container and mapping local code into it
docker run -v /Users/xunliu/Desktop/go/src/github.com/Telenav/osrm-backend:/osrm-code -it osrm-dev-experiment-cucumber:v1 /bin/bash
```

### Install node with nvm
```
curl https://raw.githubusercontent.com/creationix/nvm/v0.30.2/install.sh | bash
source $NVM_DIR/nvm.sh
// reference from https://travis-ci.org/github/Project-OSRM/osrm-backend/builds/628365424/config
nvm install 10
nvm use 10

// make sure you are under root folder of osrm's code
npm install
npm link

// I also run following command because I met errors with dependencies, they probably not needed if config correctly
npm audit fix --force
apt-get install -y cucumber
```

**Comment by CodeBear801** [comment]
## How to make it automatic run

OSRM team choose `travis-ci` for automatically check, you could go to here for more details: https://travis-ci.org/github/Project-OSRM/osrm-backend
https://travis-ci.org/github/Project-OSRM/osrm-backend/builds/628365424/config

**Comment by CodeBear801** [comment]
## How to write cucumber tests in OSRM
Here are links you could follow:
https://github.com/Project-OSRM/osrm-backend/wiki/Cucumber-Test-Suite#writing-tests
https://cucumber.io/docs/guides/10-minute-tutorial/

Here are existing feature files:
https://github.com/Telenav/osrm-backend/tree/master/features

**Comment by wangyoucao577** [comment]
> @wangyoucao577, if we plan to extend the tests and make it running on `travis-ci`, we need to spend some time to experiment setting up `node's dependencies` and make them into Dockerfile.

@CodeBear801 Very good doc for beginners. 
I think we don't need `travis-ci` anymore. The `GitHub Actions` is much better: better integration with Github, and very fast. It's ok to put `cucumber` dependecy in the `osrm-backend-dev` docker. Also, we can setup the `cucumber` test based on `GitHub Actions` directly. 
By the way, I saw the `cucumber` provides a lot of choices for installation, we can pick up the best one for us(`node` is one of the choices, aha~). https://cucumber.io/docs/installation/

**Comment by CodeBear801** [comment]
Discussion summary on 03252020 with our QA leaders, for `Using Cucumber to test TelenavNavigationSDK`

- `BDD` is not silver bullet.  We should start with small scope to verify whether it is the way to go, then iteratively make it bigger or adjust the direction 
- Define the contract between development and testing is key: From developer's perspective, he could use such contract to verify all his logic, from QA's perspective, it should be easy to represent target features
- Besides `Cucumber`, [`spock`](http://spockframework.org/) is also a BDD framework
- BDD can be expressed by `given`, `when`, `then`
    + Given some mockable condition
    + When attempting to do some operation
    + Then check expect result
    + You could find a great article here: https://martinfowler.com/bliki/GivenWhenThen.html
