### ISSUE TITLE
Wrong variable in `docker-entrypoint.sh`

### ISSUE THREAD

**Issue by serho** [Telenav/osrm-backend#309]
Hi there!

It looks like `WAYID2NODEIDS_MAPPING_FILE_COMPRESSED` is wrong variable here. It should be `${WAYID2NODEIDS_MAPPING_FILE}${SNAPPY_SUFFIX}`

https://github.com/Telenav/osrm-backend/blob/ad0d667eb08286f85b4a0be3716105a2a1afdc17/docker-orchestration/osrm-backend/docker-entrypoint.sh#L32

**Comment by wangyoucao577** [comment]
Yes, you're right! It seems that we forgot to change it during refactor. It should be `${WAYID2NODEIDS_MAPPING_FILE}${SNAPPY_SUFFIX}`.
