### ISSUE TITLE
Optimize intermediate file of <way, nodeids> mapping table

### ISSUE THREAD

**Issue by CodeBear801** [Telenav/osrm-backend#31]
We need to generate <wayid, nodeids> mapping table to enable Telenav traffic for OSRM.  More background could go to #22.
This table will be used to generate speed.csv each several minutes and be used for OSRM customization.  The initial version takes about 70~80 seconds to iterate all the table and about 10GB's memory.  
Our target is optimize time cost for dealing this file.

**Comment by CodeBear801** [comment]
Current file format:
```
wayid1,nodeid1,nodeid2,nodeid3
wayid2,nodeid4,nodeid5
...
```
Example
```
24418343,84760849102,84760850102
24418344,84760846102,84760858102,847608599102
```
Statistic
csv, 12521206024
tar, 2035689499
snappy, 3623614741
parquet, 3768399074

**Comment by CodeBear801** [comment]
After analysis source data, we feel delta strategy could be a good way to reduce original information's size.
Instead of recording
```
24418343,84760849102,84760850102
24418344,84760846102,84760858102,847608599102
```
we could record
```
wayid1, nodeid1, (nodeid2-nodeid1)
wayid2-wayid1, nodeid3-nodeid1, nodeid4-nodeid3, nodeid5-nodeid4
wayid3-wayid2, nodeid6-nodeid3,nodeid7-nodeid6
//...

wayid 1000, nodeid1000, nodeid1001-nodeid1000
//...


```

**Comment by CodeBear801** [comment]
Updates for experiment
```go
func convertWayObj2IdMappingStringCompressed(nodeids []int64, wayid int64, preNodeID int64, preWayID int64) string {
	var str string
	str += strconv.FormatInt((wayid-preWayID), 10) + ","

	for i, n := range nodeids {
		str += strconv.FormatInt((n - preNodeID), 10)
		if i < (len(nodeids) - 1) {
			str += ","
		}
		preNodeID = n
	}
	str += "\n"

	return str
}

func updateDeltaBase(wc uint32, currNodeID, currWayID int64) (int64, int64) {
	if wc%1000 == 0 {
		return 0, 0
	} else {
		return currNodeID, currWayID
	}
}
```
Result:

**Comment by wangyoucao577** [comment]
Seems good. The blob size is `wayid2nodeids` count, right?

**Comment by wangyoucao577** [comment]
How about the `snappy` compress and decompress time cost?

**Comment by CodeBear801** [comment]
> Seems good. The blob size is `wayid2nodeids` count, right?

Blob size means group count while compressing elements in wayid2nodeids.  I choose delta strategy to generate the diff, and each "Blob size" elements would reset the base.

**Comment by CodeBear801** [comment]
Back from emergent firefighting.  Will continue this task.

**Comment by CodeBear801** [comment]
Latest strategy(v4)
- Record mapping table of wayid->nodeids into snappy(12GB -> 3GB)
- When start rpc request with traffic server, start loading mapping table, write mapping table result into 64 channels(configurable)
  As long as communication with traffic server finished, which means mapping of wayid->speed is generated, start transition and dump 
  There will be 64 threads working on processing, then finally use one thread to dump

```
Processing time for getting traffic flow takes 14.504480 seconds
Processing time for building traffic map takes 6.370307 seconds
Processing time for loadWay2NodeidsTable takes 48.059116 seconds
Processing time for dumpSpeedTable4Customize takes 32.162450 seconds
```
Total time is 14 + 6 + 32, compare with v1 is 14 + 6 + 98

The strategy of V2
- one goroutine to generate traffic result(13 seconds)
- one gorouting to generate a map of wayid to nodeids array (280 seconds)
- 16 ~ 32 tread to iterate traffic array, query on map and generate final result(15 seconds)

Problem
- Load all data into system takes too much of time.  Especially the nodeids using slice will cause lots of memory allocation and deallocation
- Dump step need to wait for first two steps to finish

The strategy of V3
- one goroutine to generate traffic result(13 seconds)
-  16~64 gorouting to decoding id mapping table in delta format, put [wayid, nodeids array] into channel (100+ seconds)
- As long as step1 is finished, start dummping (100+ seconds)

Problem:
- Decoding string and put [wayid, nodeids array] has lots of additional memory usage, while is V4 I direct put string into channel, and move decoding of this string near final dump.

**Comment by CodeBear801** [comment]
Upload the cpu profile and mem profile for v2, will do more analysis and compare with v4 later.
[cpu-v2.pdf](https://github.com/Telenav/osrm-backend/files/3389296/cpu-v2.pdf)
[mem-v2.pdf](https://github.com/Telenav/osrm-backend/files/3389297/mem-v2.pdf)

**Comment by wangyoucao577** [comment]
It's awesome! It will be better if there's a data flow diagram describes the flow. 
For the 64 threads(goroutines I think), how about set it by CPU cores by default?

**Comment by CodeBear801** [comment]
@wangyoucao577 
Thanks for the suggestion.  A flow diagram is needed :)
Will do more experiments about how many goroutine is the best result.

**Comment by CodeBear801** [comment]
Some idea about next step:
#1. The original requirement of this task, is due to traffic team dropped original pbf's nodeid and we need to generate that. 
      Need to confirm with traffic team, add original node id should not hard from their side, they could put it in the rpc protocal

#2. When we consider end to end time, we will evaluate the time cost between traffic happened in the real world and when such traffic be used in our routing engine.
      Real world accident -> TomTom -> Pull & Push request from Telenav -> Traffic component -> Script in this task->OSRM customization -> Restart routing
      From what we could change, we will consider how to optimize "Script in this task->OSRM customization -> Restart routing"

#3. For the script part, if we could load way-> nodeids into memory, then the time cost would be around 20 seconds, but memory usage could be up to 10GB
      We could consider just put most frequent items into memory + in memory cache such as redis for other items.  In memory cache could be updated more frequently, such as minute level, item need redis could be updated each several minutes

#4. Currently, the biggest time cost is in OSRM Customization part, it seems each round of "OSRM customization" need about 10 minutes.
      We might need to think about using **delta strategy** to handle this, not to update everything in each round.
