### ISSUE TITLE
Profile OASIS service for charge station based routing - Round 1

### ISSUE THREAD

**Issue by CodeBear801** [Telenav/osrm-backend#345]
subtask of #344

## Initial status
Test device is mac book pro mid2014, 2.5GHZ interl Core i7, 16GB 1600 MHZ DDR3, SSD

### Profile based on North America data
Performance
| From - To   |      Distance(miles)      |  Time(seconds) | Comments
|----------|:-------------:|------:|---|
| SF to San Jose |  50  | 19  |http://127.0.0.1:8090/oasis/v1/earliest/-122.425871,37.784722;-121.554942,37.001320?max_range=500000.0&curr_range=30000.0|
| San Jose to LA |    350   |   65 |http://127.0.0.1:8090/oasis/v1/earliest/-121.876472,37.321901;-118.230489,34.064539?max_range=500000.0&curr_range=30000.0|
| Detroit to Chicago | 282 |    16 | http://127.0.0.1:8090/oasis/v1/earliest/-83.050313,42.334200;-87.684499,41.862942?max_range=500000.0&curr_range=30000.0|
| Kansas to Nashville, Tennessee | 550 |    11 |http://127.0.0.1:8090/oasis/v1/earliest/-94.587561,39.083669;-86.779198,36.161288?max_range=500000.0&curr_range=30000.0|
| Manhatten, NY to washington DC | 240 |    52 | http://127.0.0.1:8090/oasis/v1/earliest/-73.995595,40.734864;-77.038949,38.902079?max_range=500000.0&curr_range=30000.0|

Data profile

```json
{
   "count":  "comment out due to sensitive internal data source",   
   "valid_count":"comment out due to sensitive internal data source",  
   "average_nearby_ids_count":5138,
   "max_nearby_ids_count":9830,
   "min_nearby_ids_count":1,
   "average_value_max_distance":806779.9993183401,
   "max_value_max_distance":821709.1034231585,
   "min_value_max_distance":205.54475672961786,
   "average_value_max_duration":36341.44141073571,
   "max_value_max_duration":37013.92357761975,
   "min_value_max_duration":9.258772825658463,
   "maxrange_set_by_preprocessing":800000
}
```
Init time is about 30 ~ 35 seconds
```
Initialize OASIS resource manager takes 31.394521 seconds.
```

**Comment by CodeBear801** [comment]
Profiles

**Comment by CodeBear801** [comment]
Experiment

**Comment by CodeBear801** [comment]
## Issue identify
One problem is, seems golang's `map` is bottleneck for several places, such as
![image](https://user-images.githubusercontent.com/16873751/82274240-72b47680-9934-11ea-8474-528be4adbced.png)

here is the profile for several `map` count after single round
```
len(queryHeap.m) = 14912 

len(nodeGraph.adjacentList) = 6714, len(nodeGraph.edgeMetric) = 49,778,407
```
here are several links related with golang's `map`
https://www.ardanlabs.com/blog/2013/12/macro-view-of-map-internals-in-go.html
https://www.cnblogs.com/qcrao-2018/p/10903807.html

I make following modification
- reserve large size for map
- change `map` to `slice` for `nodeID2NodePtr`
- remove no use `nav.location` for now

**Comment by CodeBear801** [comment]
## Issue identify

Large amount of time related with chargingstrategy, such as
![image](https://user-images.githubusercontent.com/16873751/82274813-020e5980-9936-11ea-8a6b-7cf7617f9749.png)

Try to use fixed stable object to replace dynamic generated

## code

## Result
No change, I think might related with 
```
func (f *fakeChargeStrategy) CreateChargingStates() []State {
	return f.stateArray
// may be should record and return []*State instead of []State

```

**Comment by wangyoucao577** [comment]
In https://github.com/Telenav/osrm-backend/issues/345#issuecomment-630521108, the picture shows only 0.034% + 0.24% = 0.274%, which isn't a big cost, right?

**Comment by wangyoucao577** [comment]
From the cpu profile https://github.com/Telenav/osrm-backend/issues/345#issuecomment-630344350, memory operation and gob decoding(mostly reflect) are more hot, almost take half time. Deep dive these two might be more effective.            
 
![image](https://user-images.githubusercontent.com/1905370/82276623-5d812b80-99b8-11ea-9f5d-d4b05e239b80.png)

**Comment by CodeBear801** [comment]
> From the cpu profile [#345 (comment)](https://github.com/Telenav/osrm-backend/issues/345#issuecomment-630344350), memory operation and gob decoding(mostly reflect) are more hot, almost take half time. Deep dive these two might be more effective.
> 
> ![image](https://user-images.githubusercontent.com/1905370/82276623-5d812b80-99b8-11ea-9f5d-d4b05e239b80.png)

That one is used at initialization time, not running time. 
V3's picture is more clear, there are in different line

![image](https://user-images.githubusercontent.com/16873751/82277058-cbd3d880-993b-11ea-8ba6-e5d8664f2910.png)

**Comment by CodeBear801** [comment]
As @wangyoucao577 mentioned yesterday, I generate the wrong profile.  In my code running I keep generate `v1` but when generating png I use `v2`.  Surprisingly, when I made following change I manually typed the conversion so I got correct result. L.O.L

![image](https://user-images.githubusercontent.com/16873751/82357237-a8e80980-99b9-11ea-87b8-816045f7c366.png)
 
Finally, that 4 seconds is gone.  But during debug, I found a very interesting result: when made following changes, performance directly jump from 55 seconds to **10** seconds, problem solved.
```golang
	stateCandidates := []State{
		{
			Energy: sixtyPercentOFMaxEnergy,
		},
		//{
		//	Energy: eightyPercentOfMaxEnergy,
		//},
		//{
		//	Energy: maxEnergyLevel,
		//},
	}
```
It means the algorithm is more suite for normal routing but not EV routing yet.

## Performance result
![profile_v4_us_05192020](https://user-images.githubusercontent.com/16873751/82358001-b81b8700-99ba-11ea-809a-52b78802d40c.png)

**Comment by CodeBear801** [comment]
Another place is, after code modification in https://github.com/Telenav/osrm-backend/commit/5bcc4e2179d8263a24c3e0319d353ef32e744ce2

time used in `calcChargeTime` also dropped.


![image](https://user-images.githubusercontent.com/16873751/82358707-bd2d0600-99bb-11ea-87d7-9415a6c0d420.png)
