### ISSUE TITLE
Profile OASIS service for charge station based routing - Round 2

### ISSUE THREAD

**Issue by CodeBear801** [Telenav/osrm-backend#349]
Subtask of #344, related with #345, next step is #352 

## Result Summary

| Change Summary   |      Worst Case System Time(seconds)      |  Init Memory | Init Time(seconds) | More details
|---------------------|:----:|:------:|:---:|:---|
| master(baseline)|  49  | 3GB  | 30|https://github.com/Telenav/osrm-backend/issues/349#issuecomment-632204116|
| Round 1's modification|  38  | 3GB  | 30|https://github.com/Telenav/osrm-backend/issues/349#issuecomment-632235771|
| Avoid object converting in getConnectivities and optimization inside that function|  11  | 7.5GB  | 68|https://github.com/Telenav/osrm-backend/issues/349#issuecomment-632236884|
| Avoid heavy structure conversion, tune hash table |  5  | 7.5GB  | 68|https://github.com/Telenav/osrm-backend/issues/349#issuecomment-632383063, https://github.com/Telenav/osrm-backend/issues/349#issuecomment-632914918|

Test env: macpro(macpro 2013 32 core 64GB memory 1TB ssd)

## Major target
- Remove the time cost for generating temporary objects, move them to initialization
   + try to add a new step in `ETL`, input is current data, covert them directly into target data
   + need refactor `weight` part https://github.com/Telenav/osrm-backend/issues/348
   + try to use slice + slice instead of map + slice, **try to create logic node during initialization time**
```
// QueryResult records topological query result
type QueryResult struct {
	StationID       string
	StationLocation *nav.Location
	Distance        float64
	Duration        float64
}

// QueryResult records topological query result
type QueryResult struct {
	StationID       string
	StationLocation *nav.Location
	Weight          *Wight
}
```

![image](https://user-images.githubusercontent.com/16873751/82275221-0424e800-9937-11ea-8f17-98a81fd7b705.png)
[click here for full picture](https://user-images.githubusercontent.com/16873751/82263189-36bee880-9917-11ea-8ed6-0f87b1494731.png)

- Remove hash map of `Edge`
![image](https://user-images.githubusercontent.com/16873751/82275267-2159b680-9937-11ea-9a5b-4bef2b7ac437.png)
[click here for full picture](https://user-images.githubusercontent.com/16873751/82263189-36bee880-9917-11ea-8ed6-0f87b1494731.png)

- Use `slice` instead of `map`
```
m  map[nodeID]*queryHeapNodeInfo
m:  make(map[nodeID]*queryHeapNodeInfo, 15000), // change to slice?
```

**Comment by CodeBear801** [comment]
Tricks for performance tune, change to a powerful server.  It immediately jump to 10 seconds on macpro compare to 40~50 seconds on macbookpro.

Due to I increased the memory usage, its not sufficient to run benchmarks on 16GB of physical memory, I switched to a macpro.  

Will do the following:
- Adjust the initial benchmark to compare
- Profile for the memory differences

**Comment by CodeBear801** [comment]
Update test base line due to switch benchmark device from macbookpro to macpro(macpro 2012 32 core 64GB memory 1TB ssd)

**Comment by CodeBear801** [comment]
Testing for Round 1's result on macpro

## System time

```
Generate solutions for charge station based routing takes 38.902622 seconds.
```

## CPU profile
![cpu_round1_05212020](https://user-images.githubusercontent.com/16873751/82586626-ba154f80-9b4c-11ea-8bc0-abb027e9606b.png)



## Memory profile
No change

**Comment by CodeBear801** [comment]
Test based on commit https://github.com/Telenav/osrm-backend/commit/13283547908b355b9194bbcb3011f20047ae5bf1 in task #348

**Comment by CodeBear801** [comment]
Next step:
- Optimize the ID converter part, all use PlaceID
- Optimize for location querier part
- Optimize `Edge` hash map

**Comment by CodeBear801** [comment]
Finally, I got a slim version of curve

For the result, I think I could make it fall into 1 seconds by
- pre-process data, provide functionality of getting `place` to `place` `weight` directly.  
- pre-process data, not directly dump go's map by `gob`, but using `slice` to record data, I think it will make init time around 2~5 seconds and memory taken is about 1~2GB

![cpu_05222020](https://user-images.githubusercontent.com/16873751/82710492-d9d57200-9c37-11ea-9716-f895a43a4749.png)

**Comment by wangyoucao577** [comment]
The summary in https://github.com/Telenav/osrm-backend/issues/349#issue-620610955 show significant improvement. However, it's a little bit difficult to me to figure out what really changed affect the performance from both the change summary and commit.  Will you please consider to re-orignaize and describe them in a read friendly way? That would be helpful for other guys too. Haha~

**Comment by CodeBear801** [comment]
> The summary in [#349 (comment)](https://github.com/Telenav/osrm-backend/issues/349#issue-620610955) show significant improvement. However, it's a little bit difficult to me to figure out what really changed affect the performance from both the change summary and commit. Will you please consider to re-orignaize and describe them in a read friendly way? That would be helpful for other guys too. Haha~

Too many changes in unit test, but I do need to summary it more clearly.

**Comment by CodeBear801** [comment]
![image](https://user-images.githubusercontent.com/16873751/82957890-e83dc980-9f68-11ea-944b-1da121d63540.png)

**Comment by wangyoucao577** [comment]
Try to summary the improvements:      
- Reduced `map` size;    
- Used `slice` instead of `map` when possible to improve querying performance;    
- Removed unncessarily mass object transforming(i.e., use same `*nav.Location`);      
- Removed unncessarily mass `string` to `int` parsing;       
- Overall reduced a lot of unncessarily object allocation.     

Did I missed anything?

**Comment by CodeBear801** [comment]
> Try to summary the improvements:
> 
> * Reduced `map` size;
> * Used `slice` instead of `map` when possible to improve querying performance;
> * Removed unnecessarily mass object transforming(i.e., use same `*nav.Location`);
> * Removed unnecessarily mass `string` to `int` parsing;
> * Overall reduced a lot of unnecessarily object allocation.
> 
> Did I missed anything?

That's all the changes.
