### ISSUE TITLE
traffic process statistics

### ISSUE THREAD

**Issue by wangyoucao577** [Telenav/osrm-backend#43]
Statistics not only process time, but also data count/size.Now we already have `got flows count: 16130303, time used: 12.398055 seconds`, but still need more.     
E.g.     
- how many `traffic flows` in the generated flows map
- how many `wayid-nodeids` loaded 
- how many `traffic flows` have been touched
  - how many forward
  - how many backward
  - how many related wayids 
  - how many related nodeids
- how many `fromnode,tonode,speed` generated

**Comment by CodeBear801** [comment]
Implement the first version

Processing time for getting traffic flow takes 12.162744 seconds
Load map[wayid] to speed with 16130303 items, 8067324 forward and 8062979 backward.
Processing time for building traffic map takes 6.719450 seconds
Open output file of traffic.csv succeed.
Processing time for loadWay2NodeidsTable takes 47.764592 seconds
Processing time for dumpSpeedTable4Customize takes 59.973945 seconds
Statistic: 
Load 58663716 way from data with 608395109 nodes.
9183418 way with 50908411 nodes matched with traffic record.
Generate 71424797 records in final result with 35713263 of them from forward traffic and 35711534 from backword.

**Comment by CodeBear801** [comment]
I implement a class to update statistic
```go
func (d* dumperStatistic) update(wayCnt uint64, nodeCnt uint64, fwdRecordCnt uint64, 
	bwdRecordCnt uint64, wayMatchedCnt uint64, nodeMatchedCnt uint64) {
	d.mu.Lock()
	defer d.mu.Unlock()
	
	d.wayCnt += wayCnt
	d.nodeCnt += nodeCnt
	d.fwdRecordCnt += fwdRecordCnt
	d.bwdRecordCnt += bwdRecordCnt
	d.wayMatchedCnt += wayMatchedCnt
	d.nodeMatchedCnt += nodeMatchedCnt
}

```
For each of go routine just call this function for one time, but I found that it has impact on final performance due to too many goroutines.  Tomorrow will change to using channel to pass the object for updating each goroutine's result.

**Comment by wangyoucao577** [comment]
Do we have some way to show the speed by red/yellow/green on map? It will be helpful to see whether traffic involved if possible.

**Comment by CodeBear801** [comment]
osrm frontend is the one OSRM team used to check traffic, but which is color mapping based on speed from OSRM not represent for traffic, while what we want is some kind of speed.category or live speed compare with default speed.

We might consider to show 2 layer of traffic on map
- segment coloring from OSRM frontend, which represent final speed for each segment
- traffic tile's coloring strategy
We could enable either one of them to show final speed.

**Comment by CodeBear801** [comment]
After statistic, I found the place where the issue is:

![image](https://user-images.githubusercontent.com/16873751/61482370-4d8b5c00-a94f-11e9-8c88-7237f0bbac22.png)

We generate double information compare with previous version, its not related with statistic.

**Comment by CodeBear801** [comment]
I think the main reason is, current version of traffic.csv double the contents compare with previous version.
```
connect traffic proxy 10.189.100.132:6666
getting flows
Open idsmapping file of na.original.csv.snappy succeed.
got flows count: 16130303
Processing time for getting traffic flow takes 14.831700 seconds
Load map[wayid] to speed with 16130303 items, 8067324 forward and 8062979 backward.
Processing time for building traffic map takes 7.068428 seconds
Open output file of traffic.csv succeed.
Processing time for loadWay2NodeidsTable takes 48.057856 seconds
Processing time for dumpSpeedTable4Customize takes 59.122249 seconds
Statistic: 
Load 58663716 way from data with 608395109 nodes.
9183418 way with 50908411 nodes matched with traffic record.
Generate 71424797 records in final result with 35713263 of them from forward traffic and 35711534 from backward.
```

**Comment by CodeBear801** [comment]
Compare with previous version, traffic.csv file double its size
```
-rwxr-xr-x 1 mapuser appuser  2549211851 Jul 18 13:57 traffic.csv
```
