### ISSUE TITLE
Topics for Jay's travel to US 

### ISSUE THREAD

**Issue by CodeBear801** [Telenav/osrm-backend#48]
- [x] OSRM customization -> Can we limit this part's time cost
- [x] OSRM facade -> How to abstract common API
- [x] OSRM cost model + lua
- [x] OSRM routed initialization(memory map vs shared memory)

[optional]
- [x] lane based routing
- [ ] Tegola -> Vector tile engine written by go
- [ ] Microservice -> gRPC, Istio, K8s, Zipkin, Skaffold, OpenCensus
- [x] Cloud map matching

**Comment by wangyoucao577** [comment]
- lane based routing

**Comment by CodeBear801** [comment]
OSRM routed initialization(memory map vs shared memery)

**Comment by CodeBear801** [comment]
[optional]
Cloud map matching

**Comment by wangyoucao577** [comment]
https://github.com/Telenav/osrm-backend/issues/30#issuecomment-516637584 describes our breakdown for "OSRM customization -> Can we limit this part's time cost".

**Comment by wangyoucao577** [comment]
https://github.com/Telenav/osrm-backend/issues/30#issuecomment-517485200 describes our design and breakdown for datafacade and initializationmemory(mmap, sharedmemory).

**Comment by CodeBear801** [comment]
This document record the discussion between Perry, Jay, Haifeng about Map matching:
https://github.com/Telenav/open-source-spec/blob/master/osrm/doc/osrm_mapmatching.md
