### ISSUE TITLE
Handle one way tags from professional data

### ISSUE THREAD

**Issue by CodeBear801** [Telenav/osrm-backend#61]
OSM data represent oneway using from node -> to node + oneway=yes
Professional data doesn't reverse this and using "to node-> from node" + oneway=-1 to represent  oneway.

**Comment by wangyoucao577** [comment]
From the [Key:oneway](https://wiki.openstreetmap.org/wiki/Key:oneway), OSM data also can use `oneway=-1` to represent reverse direction is open.

**Comment by wangyoucao577** [comment]
Also some logic to handle the `oneway=-1` in `Lua` code: 

https://github.com/Telenav/osrm-backend/blob/7677b8513bf8cdbadb575c745acf4f9124887764/profiles/lib/way_handlers.lua#L569-L572

**Comment by CodeBear801** [comment]
That's great.  
I guess we need specific test cases to verify such situation.
Another case need to be confirmed is conditional oneway, cases like in the morning go into town and afternoon go out of town.
