### ISSUE TITLE
Enable ELK stack for OSRM

### ISSUE THREAD

**Issue by CodeBear801** [Telenav/osrm-backend#65]
We want to use ElasticSearch to collect OSRM's logs and Kibana for visualize result.

Tasks(more could coming later)

- [x] Use docker compose to setup ELK stack
- [x] Send OSRM's log to elastic search
- [x] Build visualization dash board in Kibana

**Comment by CodeBear801** [comment]
Status update:
Finished the experiment of using docker compose to set up ELK stack.

- Use Filebeat to collect OSRM logs
   Enable metricbeat/packagebeat
- Filebeat will responsible transfer data into elasticsearch
- Kibana will reflect status in elasticsearch
- Might need manage the data size in elasticsearch
```
#/bin/bash
#es-index-clear
LAST_DATA=`date -d "-15 days" "+%Y.%m.%d"`
curl -XDELETE 'http://ip:port/*-'${LAST_DATA}'*'
```

**Comment by wangyoucao577** [comment]
Do we need structure logs in the future? I saw some log system defaultly structure logs as JSON to easy to store.

**Comment by CodeBear801** [comment]
Agree.  JSON format could enable lots of things.  
For the first step I want to enable end-to-end integration, I want to import following log
```
[2019-08-13T05:27:01 UTC] [info] 13-08-2019 05:27:01 5.28196ms 10.189.160.19 - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36 200 /tile/v1/car/tile(5258,12698,15).mvt
[2019-08-13T05:27:01 UTC] [info] 13-08-2019 05:27:01 0.491444ms 10.189.160.19 - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36 200 /tile/v1/car/tile(5259,12696,15).mvt
[2019-08-13T05:27:01 UTC] [info] 13-08-2019 05:27:01 1.04668ms 10.189.160.19 - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36 200 /tile/v1/car/tile(5259,12697,15).mvt
```
And maybe latter docker related information(CPU, memory, etc)

**Comment by CodeBear801** [comment]
Status update:
Logs in /osrm output folder has been showed in Kibana
![image](https://user-images.githubusercontent.com/16873751/66614832-4b682080-eb7f-11e9-8594-212892849865.png)

## How
- In Filebeat, config a folder which contains osrm logs
```
- input_type: log
  paths:
    - /var/log/osrm/*.log*
```
- Filebeat will upload data to Elasticsearch, and then using Kibana to visualize result

## Next Step
-

**Comment by CodeBear801** [comment]
## Updates
- Using File Beat won't break logs, each line of log will generate as 'message'
- Need logstash to generate filter patterns and collect information we needed, such as 
```
[2019-08-06T11:47:42 UTC] [info] Used 76202107 speeds from traffic.csv
```

## Next Step
- Using company's stack to set up ELK pipeline
- Generate 1 ~ 2 dashboard for viewing result
- Using docker-compose way need to change import from FileBeat to Logstash, I will put this one as lower priority.  

## Discussions

![image](https://user-images.githubusercontent.com/16873751/66672995-82d4dc80-ec14-11e9-9714-3a1622e56b63.png)

**Comment by CodeBear801** [comment]
## Updates
- Set up ELK stack for OSRM on local, wrote two filters, one for live traffic speed and one for request url.  The input is log location and using "docker compose up" set up all the environment.
- Set up ELK stack based on Telenav's technical stack

## Result
![image](https://user-images.githubusercontent.com/16873751/66879145-d70ff180-ef71-11e9-9357-bfb244de90fe.png)
![image](https://user-images.githubusercontent.com/16873751/66879168-e858fe00-ef71-11e9-9e62-294b2320896b.png)
![image](https://user-images.githubusercontent.com/16873751/66879183-f3139300-ef71-11e9-8b63-0354408dd6a9.png)
![image](https://user-images.githubusercontent.com/16873751/66879200-06266300-ef72-11e9-809a-226ec89b05f8.png)

## To do
- Build visualize map for traffic-speed-update count
- Decoding uri string, get detail parameters, such as(route request, tile request, etc) and related parameters

**Comment by CodeBear801** [comment]
Decoding example

Case 1:

```
[2019-08-06T11:47:42 UTC] [info] Used 535602493 speeds from LUA profile or input map
```
Grok
```
\[%{TIMESTAMP_ISO8601:timestamp} UTC\] \[%{LOGLEVEL:log-level}\] Used %{NUMBER:lua-speed-items} speeds from LUA profile or input map
```

Case 2:
```
[2019-08-13T05:25:48 UTC] [info] 13-08-2019 05:25:48 0.503655ms 111.189.160.19 - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36 200 /tile/v1/car/tile(5259,12696,15).mvt
[2019-08-13T05:25:48 UTC] [info] 13-08-2019 05:25:48 0.503655ms 111.189.160.19 - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36 200 /table/v1/driving/13.388860,52.517037;13.397634,52.529407;13.428555,52.523219
```
grok
```
\[%{TIMESTAMP_ISO8601:timestamp} UTC\]\s\[%{LOGLEVEL:log-level}\]\s%{DATE_EU:request-date}\s%{TIME:request-time}\s%{DATA:response_duration}\s%{IP:request-ip}\s\W\s(?<user-agent>.+?(?=\s\d{3}\s))\s(?<response-code>\d{3})\s%{URIPATH:uri}
```


[small.log](https://github.com/Telenav/osrm-backend/files/3732077/small.log)

**Comment by CodeBear801** [comment]
![image](https://user-images.githubusercontent.com/16873751/66962573-2dd70300-f026-11e9-9963-6dd521dc2c17.png)

**Comment by wangyoucao577** [comment]
How about display curve instead of histogram?

**Comment by CodeBear801** [comment]
We could also add which into dashboard.

**Comment by CodeBear801** [comment]
I think what we expected is: when traffic update under certain value, we could get a warning.
After take a look at following two pages:
https://www.elastic.co/guide/en/kibana/7.1/watcher-create-threshold-alert.html
https://www.elastic.co/guide/en/elasticsearch/reference/7.4/watcher-getting-started.html

I think which need additional license for that purpose.  Need more research.
