### ISSUE TITLE
Discuss C++11 grammar 

### ISSUE THREAD

**Issue by CodeBear801** [Telenav/osrm-backend#72]
- In the function of [reorderFirstLast](https://github.com/Telenav/osrm-backend/blob/ce5120f8c1f752c51c931b1ce193809a7aa94749/include/partitioner/reorder_first_last.hpp#L18)
```
    const auto flipped = [](auto fn) {
        return [fn](auto &&lhs, auto &&rhs) {
            return fn(std::forward<decltype(lhs)>(rhs), std::forward<decltype(rhs)>(lhs));
        };
    };
```
Q: why not 
```
fn(std::forward<decltype(rhs)>(rhs), std::forward<decltype(lhs)>(lhs))
```
Is it due to the use of reverse_iterator?

- In my example of https://github.com/Telenav/open-source-spec/blob/master/osrm/doc/osrm_c%2B%2B_examples.md#stdforward, for the sample code here: cpp.sh/8kv3r, why can't I use this strategy
```
MatchParameters param2(true, true, std::move(waypoints),{});
// C++ could accept MatchParameters param2(true, true, std::move(waypoints)), which means nothing for std::forward<Args>(args_)..., but if using empty array_list{}, seems C++ could not deduce correct type, is that due to based on {} we could not deduce T in vector<T>?
```

**Comment by wangyoucao577** [comment]
For the first question, please take care of:    

1. the function name `flipped`
In its implementation, it's really did the `flipped` thing by `std::forward<decltype(lhs)>(rhs)` and `std::forward<decltype(lhs)>(rhs)`. In another word, it changes the default `comp` behavior from compare `lhs/rhs` to `rhs/lhs`.      
In later usage, the code looks like `flipped(comp)`. 
https://github.com/Telenav/osrm-backend/blob/ce5120f8c1f752c51c931b1ce193809a7aa94749/include/partitioner/reorder_first_last.hpp#L41

2. I think it can be said that related to `reverse_iterator`. 
The first `std::nth_element` is used to find the `n` smallest elements and move them to the beginning, and the second one is used to find the `n` biggest elements and move them to the end.

**Comment by wangyoucao577** [comment]
For your second question, I'm not sure whether I understand your question well. 
But the answer can be yes, `C++` can not deduce an empty `{}` to `vector<int>`. 
If you write something like `auto a = {100};`, the type of `a` will be `std::initializer_list<int>` mostly. See [effective-modern-cpp/item-2-understand-auto-type-deduction#different-part](https://github.com/wangyoucao577/modern-cpp/tree/master/effective-modern-cpp/item-2-understand-auto-type-deduction#different-part)

In your implementation, use `vector<int>{}` should work. 
I.e. `MatchParameters param3(true, true, std::move(waypoints), std::vector<int>{});`

**Comment by CodeBear801** [comment]
> For your second question, I'm not sure whether I understand your question well.
> But the answer can be yes, `C++` can not deduce an empty `{}` to `vector<int>`.
> If you write something like `auto a = {100};`, the type of `a` will be `std::initializer_list<int>` mostly. See [effective-modern-cpp/item-2-understand-auto-type-deduction#different-part](https://github.com/wangyoucao577/modern-cpp/tree/master/effective-modern-cpp/item-2-understand-auto-type-deduction#different-part)
> 
> In your implementation, use `vector<int>{}` should work.
> I.e. `MatchParameters param3(true, true, std::move(waypoints), std::vector<int>{});`

Agree, I think might be something like this, but you clearly mentioned that vector<int>{}

**Comment by CodeBear801** [comment]
> For the first question, please take care of:
> 
> 1. the function name `flipped`
>    In its implementation, it's really did the `flipped` thing by `std::forward<decltype(lhs)>(rhs)` and `std::forward<decltype(lhs)>(rhs)`. In another word, it changes the default `comp` behavior from compare `lhs/rhs` to `rhs/lhs`.
>    In later usage, the code looks like `flipped(comp)`.
>    https://github.com/Telenav/osrm-backend/blob/ce5120f8c1f752c51c931b1ce193809a7aa94749/include/partitioner/reorder_first_last.hpp#L41
> 2. I think it can be said that related to `reverse_iterator`.
>    The first `std::nth_element` is used to find the `n` smallest elements and move them to the beginning, and the second one is used to find the `n` biggest elements and move them to the end.

Yes, that's the functionality of this part.  Just hard to understand using `std::forward<decltype(lhs)>(rhs)`
I think I could understand like this, it tried to follow the exception of `Comparator comp` to pass into the exact expression for reverse search.
