### ISSUE TITLE
Split docker image(within mapdata) to smaller layers

### ISSUE THREAD

**Issue by wangyoucao577** [Telenav/osrm-backend#95]
Currently we use `docker commit` to create new docker image after data complied. It causes the last layer(mainly mapdata) too big, e.g. about 50GB for na. It's too big for docker registry. There's timeout in our docker registry that limits `docker push` time for each layer, so we have to split this layer to smaller layers to avoid `docker push` timeout.

Solution: 
- create another Dockerfile to generate new image within compiled mapdata instead of `docker commit` 
  - in the Dockerfile, each compiled mapdata file will be packaged as one docker layer 
- create another jenkins job to do this, which takes 3 parameters
  - `Telenav/osrm-backend` docker image 
  - compiled mapdata `.tar.gz` 
  - Dockerfile(use Git branch to indicate where the Dockerfile is)

**Comment by vulturm** [comment]
Do you really need this data to reside inside the image?
Couldn't it be mounted as a volume inside the container during run time ?

**Comment by wangyoucao577** [comment]
You're right, we don't need the data inside image for long-term. It's my short-term workaround since it's easy to implement. But mount as a volume into container is also not good enough, because we're deploying in kubernetes cluster, and we can not prepare the data in kubernetes node's disk, otherwise it's not easy to extend. 
As I metioned in https://github.com/Telenav/osrm-backend/issues/93, I think the long-term solution should be inject mapdata when container startup, but how to inject it will be a problem. Maybe we can use AWS EFS or similar thing. I'm not sure whether kubernetes have anything similar like docker image also can automatically distributed to each node, then the startup could be fast.

**Comment by vulturm** [comment]
EFS mounted volume shared across all k8s nodes would work too.

**Comment by wangyoucao577** [comment]
@vulturm  But I'm worrying about performance. 
I heard that the AWS EFS is network mount based, but we're using kubernetes rolling update to customize live traffic per several minutes. (please refer to https://github.com/Telenav/osrm-backend/blob/master-telenav/integration/doc/osrm-with-telenav-traffic.md for more details). 
If every container have to copy data from network to memory, the performance will be very bad for the huge size data(e.g. for NA it's about 50GB).

**Comment by vulturm** [comment]
Have you made any tests between EBS and EFS ?
EBS is still over network is not local disk on the instance.

**Comment by wangyoucao577** [comment]
Not yet.
